//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneContactFilter", Namespace="http://mycompany.com/phonebook")]
    public partial class PhoneContactFilter : object
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PhoneNumberField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedItemsOfPhoneContact", Namespace="http://mycompany.com/phonebook")]
    public partial class PagedItemsOfPhoneContact : object
    {
        
        private PhoneBook.PhoneContact[] ItemsField;
        
        private int TotalCountField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PhoneBook.PhoneContact[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneContact", Namespace="http://mycompany.com/phonebook")]
    public partial class PhoneContact : object
    {
        
        private int IdField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PhoneNumberField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mycompany.com/phonebook", ConfigurationName="PhoneBook.PhoneBookServiceSoap")]
    public interface PhoneBookServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/phonebook/GetContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<PhoneBook.GetContactsResponse> GetContactsAsync(PhoneBook.GetContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/phonebook/GetContact", ReplyAction="*")]
        System.Threading.Tasks.Task<PhoneBook.GetContactResponse> GetContactAsync(PhoneBook.GetContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/phonebook/CreateContact", ReplyAction="*")]
        System.Threading.Tasks.Task<PhoneBook.CreateContactResponse> CreateContactAsync(PhoneBook.CreateContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/phonebook/UpdateContact", ReplyAction="*")]
        System.Threading.Tasks.Task<PhoneBook.UpdateContactResponse> UpdateContactAsync(PhoneBook.UpdateContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mycompany.com/phonebook/DeleteContact", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteContactAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacts", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.GetContactsRequestBody Body;
        
        public GetContactsRequest()
        {
        }
        
        public GetContactsRequest(PhoneBook.GetContactsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class GetContactsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PhoneBook.PhoneContactFilter filter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sortColumn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sortOrder;
        
        public GetContactsRequestBody()
        {
        }
        
        public GetContactsRequestBody(PhoneBook.PhoneContactFilter filter, int pageNumber, int pageSize, string sortColumn, string sortOrder)
        {
            this.filter = filter;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
            this.sortColumn = sortColumn;
            this.sortOrder = sortOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactsResponse", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.GetContactsResponseBody Body;
        
        public GetContactsResponse()
        {
        }
        
        public GetContactsResponse(PhoneBook.GetContactsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class GetContactsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PhoneBook.PagedItemsOfPhoneContact GetContactsResult;
        
        public GetContactsResponseBody()
        {
        }
        
        public GetContactsResponseBody(PhoneBook.PagedItemsOfPhoneContact GetContactsResult)
        {
            this.GetContactsResult = GetContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContact", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.GetContactRequestBody Body;
        
        public GetContactRequest()
        {
        }
        
        public GetContactRequest(PhoneBook.GetContactRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class GetContactRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetContactRequestBody()
        {
        }
        
        public GetContactRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactResponse", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.GetContactResponseBody Body;
        
        public GetContactResponse()
        {
        }
        
        public GetContactResponse(PhoneBook.GetContactResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class GetContactResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PhoneBook.PhoneContact GetContactResult;
        
        public GetContactResponseBody()
        {
        }
        
        public GetContactResponseBody(PhoneBook.PhoneContact GetContactResult)
        {
            this.GetContactResult = GetContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContact", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.CreateContactRequestBody Body;
        
        public CreateContactRequest()
        {
        }
        
        public CreateContactRequest(PhoneBook.CreateContactRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class CreateContactRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PhoneBook.PhoneContact contact;
        
        public CreateContactRequestBody()
        {
        }
        
        public CreateContactRequestBody(PhoneBook.PhoneContact contact)
        {
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContactResponse", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.CreateContactResponseBody Body;
        
        public CreateContactResponse()
        {
        }
        
        public CreateContactResponse(PhoneBook.CreateContactResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class CreateContactResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateContactResult;
        
        public CreateContactResponseBody()
        {
        }
        
        public CreateContactResponseBody(int CreateContactResult)
        {
            this.CreateContactResult = CreateContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContact", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.UpdateContactRequestBody Body;
        
        public UpdateContactRequest()
        {
        }
        
        public UpdateContactRequest(PhoneBook.UpdateContactRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class UpdateContactRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PhoneBook.PhoneContact contact;
        
        public UpdateContactRequestBody()
        {
        }
        
        public UpdateContactRequestBody(PhoneBook.PhoneContact contact)
        {
            this.contact = contact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContactResponse", Namespace="http://mycompany.com/phonebook", Order=0)]
        public PhoneBook.UpdateContactResponseBody Body;
        
        public UpdateContactResponse()
        {
        }
        
        public UpdateContactResponse(PhoneBook.UpdateContactResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mycompany.com/phonebook")]
    public partial class UpdateContactResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateContactResult;
        
        public UpdateContactResponseBody()
        {
        }
        
        public UpdateContactResponseBody(bool UpdateContactResult)
        {
            this.UpdateContactResult = UpdateContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PhoneBookServiceSoapChannel : PhoneBook.PhoneBookServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PhoneBookServiceSoapClient : System.ServiceModel.ClientBase<PhoneBook.PhoneBookServiceSoap>, PhoneBook.PhoneBookServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PhoneBookServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PhoneBookServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PhoneBookServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneBookServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PhoneBookServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneBookServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PhoneBookServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneBookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PhoneBook.GetContactsResponse> PhoneBook.PhoneBookServiceSoap.GetContactsAsync(PhoneBook.GetContactsRequest request)
        {
            return base.Channel.GetContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PhoneBook.GetContactsResponse> GetContactsAsync(PhoneBook.PhoneContactFilter filter, int pageNumber, int pageSize, string sortColumn, string sortOrder)
        {
            PhoneBook.GetContactsRequest inValue = new PhoneBook.GetContactsRequest();
            inValue.Body = new PhoneBook.GetContactsRequestBody();
            inValue.Body.filter = filter;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            inValue.Body.sortColumn = sortColumn;
            inValue.Body.sortOrder = sortOrder;
            return ((PhoneBook.PhoneBookServiceSoap)(this)).GetContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PhoneBook.GetContactResponse> PhoneBook.PhoneBookServiceSoap.GetContactAsync(PhoneBook.GetContactRequest request)
        {
            return base.Channel.GetContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<PhoneBook.GetContactResponse> GetContactAsync(int id)
        {
            PhoneBook.GetContactRequest inValue = new PhoneBook.GetContactRequest();
            inValue.Body = new PhoneBook.GetContactRequestBody();
            inValue.Body.id = id;
            return ((PhoneBook.PhoneBookServiceSoap)(this)).GetContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PhoneBook.CreateContactResponse> PhoneBook.PhoneBookServiceSoap.CreateContactAsync(PhoneBook.CreateContactRequest request)
        {
            return base.Channel.CreateContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<PhoneBook.CreateContactResponse> CreateContactAsync(PhoneBook.PhoneContact contact)
        {
            PhoneBook.CreateContactRequest inValue = new PhoneBook.CreateContactRequest();
            inValue.Body = new PhoneBook.CreateContactRequestBody();
            inValue.Body.contact = contact;
            return ((PhoneBook.PhoneBookServiceSoap)(this)).CreateContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PhoneBook.UpdateContactResponse> PhoneBook.PhoneBookServiceSoap.UpdateContactAsync(PhoneBook.UpdateContactRequest request)
        {
            return base.Channel.UpdateContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<PhoneBook.UpdateContactResponse> UpdateContactAsync(PhoneBook.PhoneContact contact)
        {
            PhoneBook.UpdateContactRequest inValue = new PhoneBook.UpdateContactRequest();
            inValue.Body = new PhoneBook.UpdateContactRequestBody();
            inValue.Body.contact = contact;
            return ((PhoneBook.PhoneBookServiceSoap)(this)).UpdateContactAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteContactAsync(int id)
        {
            return base.Channel.DeleteContactAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PhoneBookServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PhoneBookServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PhoneBookServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59404/PhoneBookService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PhoneBookServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59404/PhoneBookService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PhoneBookServiceSoap,
            
            PhoneBookServiceSoap12,
        }
    }
}
